site_name: "The Data&AI Space"
site_author: Radu Gheorghiu
site_url: http://radugheorghiu.com

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/radu-gheorghiu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gheorghiuradu/
    - icon: material/email
      link: mailto:radu_gheorghiu@live.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/raduqq
    - icon: fontawesome/brands/medium
      link: https://medium.com/@raduq
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/1266737/radu-gheorghiu

plugins:
  - blog:
      authors_file: "{blog}/.authors.yml"
      blog_dir: .
      categories: true
      categories_url_format: "category/{slug}"
      pagination: true
      pagination_per_page: 8
  - search
  - tags:
      enabled: true

nav:
  - index.md

copyright: Copyright &copy; 2024 Radu Gheorghiu

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
  palette:
    - accent: deep orange
      primary: indigo
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - accent: indigo
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          name: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: '#'