authors:
  radugheorghiu:
    name: Radu Gheorghiu
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/1975863?v=4
    slug: https://www.linkedin.com/in/gheorghiuradu/
    url: https://www.linkedin.com/in/gheorghiuradu/